### ISSUE TITLE
data for chaostomb

### ISSUE THREAD

**Issue by geofflangenderfer** [depp/chaostomb#1]
Any chance you could make the data available you used in this post?:

https://www.moria.us/articles/chaos-tomb-visualizing-gameplay-with-d3-and-sql/

**Comment by depp** [comment]
I still have the original data around, I'm looking into posting it.

**Comment by geofflangenderfer** [comment]
Thank you. I'm looking to practice SQL and this data is actually
interesting.

**Comment by depp** [comment]
https://www.moria.us/articles/chaos-tomb-visualizing-gameplay-with-d3-and-sql/analytics.sql.gz

**Comment by depp** [comment]
Note that this is for PostgreSQL, and may require modifications for other SQL engines.
